export interface UserInfo {
  first: string;
  last: string;
  dob: string;
  ssn: string;
  address: string;
  city: string;
  state: string;
  zip: string;
}

export type ImpactLevel = 'High' | 'Medium' | 'Low' | 'Positive';
export type PriorityLevel = 'High' | 'Medium' | 'Low';
export type DisputeStrength = 'Strong' | 'Moderate' | 'Weak';
export type DisputeCategory =
  | 'Not Mine'
  | 'Inaccurate Information'
  | 'Balance/Status Error'
  | 'Obsolete (Past Reporting Limit)'
  | 'Unverifiable Debt'
  | 'Re-Aged Account'
  | 'Duplicate Entry'
  | 'Account Closed/Paid Incorrectly'
  | 'Unauthorized Inquiry'
  | 'Late Payment Error'
  | 'Collection Not Validated';

export interface CreditScore {
  bureau: string;
  score: number | null;
  rating: string;
}

export interface NegativeItem {
  priority: PriorityLevel;
  creditor: string;
  accountNumber: string;
  type: string;
  balance: string;
  status: string;
  dateReported: string;
  reasons: string[];
  impact: PriorityLevel;
  impactPoints: string;
  laws: string[];
  recommendedAction: string;
  /** Which bureaus actually report this item — only the ones present in the report */
  bureaus: string[];
  /** The single bureau to target first — chosen by AI as where the inaccuracy is most clearly documented */
  primaryBureau: string;
  /** FCRA-based category classifying why this item is disputable */
  disputeCategory: DisputeCategory;
  /** Date of First Delinquency extracted from the report (null if not found) */
  dofd: string | null;
  /** Reporting deadline: ~7 yrs + 180 days from DOFD (null if DOFD unknown) */
  reportingDeadline: string | null;
  /** True if the item's reporting deadline has already passed */
  pastReportingLimit: boolean;
  /** Estimated likelihood this dispute will succeed */
  disputeStrength: DisputeStrength;
  /** One sentence describing the exact violation and why it's disputable */
  specificViolation: string;
}

export interface ActionItem {
  title: string;
  description: string;
  impact: ImpactLevel;
}

export interface Bureau {
  key: string;
  name: string;
  color: string;
  abbr: string;
  addr: string;
}

export type DisputeStatus = 'sent' | 'responded' | 'resolved' | 'expired';
export type SendMethod = 'auto' | 'manual';

export interface DisputeRecord {
  id: string;
  user_id: string | null;
  creditor: string;
  account_number: string;
  bureau_key: string;
  dispute_category: string;
  send_method: SendMethod;
  sent_at: string;
  lob_letter_id: string | null;
  lob_tracking_number: string | null;
  expected_response_by: string;
  status: DisputeStatus;
  created_at: string;
}

export interface AnalysisResult {
  /** Stamped server-side after AI response — not generated by the AI */
  completedAt: string;
  summary: string;
  scores: CreditScore[];
  overall: {
    rating: string;
    /** 0–100, drives the donut chart */
    health: number;
    summary: string;
  };
  strengths: string[];
  weaknesses: string[];
  negativeItems: NegativeItem[];
  actionPlan: ActionItem[];
  stats: {
    totalAccounts: number;
    negativeItemCount: number;
    latePayments: number;
    hardInquiries: number;
    /** e.g. "18%" */
    utilization: string;
    /** e.g. "50–120" */
    estimatedImprovement: string;
  };
}
